default:
  models:
    Team: read
    Membership:
      - read
      - search
    Platform::Application: read
    Webhooks::Outgoing::Endpoint: manage
    Webhooks::Outgoing::Event: read
    Webhooks::Outgoing::Delivery: read
    Webhooks::Outgoing::DeliveryAttempt: read
    Invitation:
      - read
      - create
      - destroy

admin:
  manageable_roles:
    - admin
    - client
  models:
    Project: manage
    Team: manage
    Membership: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept: manage
    Platform::Application: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcepts::Collaborator: manage

client:
    Project: read
